// <auto-generated />
namespace ParkingMaster.DataAccess.Migrations.UserDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_Lots_AND_Spots_AND_Vehicles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Lots_AND_Spots_AND_Vehicles));
        
        string IMigrationMetadata.Id
        {
            get { return "201904232305592_Add_Lots_AND_Spots_AND_Vehicles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
